on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
        env:
          PAT: ${{ secrets.PAT }}
          REPO: ${{ github.repository }}
          ASSIGNEE: bulricht
      - name: rocrate-to-sembench
        uses: vliz-be-opsci/rocrate-to-sembench@main
        env:
          PROFILE: https://data.emobon.embrc.eu/observatory-profile/0.1
      - name: semantify
        uses: vliz-be-opsci/semantify@main
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
