on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'
env:
  PROFILE: https://data.emobon.embrc.eu/observatory-profile/0.11 # is duplicated in config/workflow_properties.yml
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
        env:
          PAT: ${{ secrets.PAT }}
          REPO: ${{ github.repository }}
          ASSIGNEE: bulricht
      - name: rocrate-sembench-setup
        uses: vliz-be-opsci/rocrate-sembench-setup@main
        env:
          PROFILE: '$PROFILE'
      - name: semantify
        uses: vliz-be-opsci/semantify@main
      - name: rocrate-to-pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
      - name: actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: workflow run
